server:
  port: 8086
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oldgarlic/spring-cloud
      #          search-paths: respo
      label: master
  application:
    name: config-server

