server:
  port: 8088

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    #是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false。
    #设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka
